[package]
description = "Proc macros for ticklog"
edition = "2024"
license = "MIT OR Apache-2.0"
name = "ticklog-macros"
repository = "https://github.com/tensorbinge/ticklog"
rust-version = "1.85"
version = "0.2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = {version = "3", features = ["full"]}
